segment_syns={'1':['PB2','segment 1', 'segment: 1','chromossome: 1'],'2':['PB1','segment 2','PB1-F2','segment: 2'],'3':['PA','segment 3','PA-X','segment: 3'],
              '4':['hemagglutinin','haemagglutinin','HA1','HA2','HA','segment 4','segment: 4'],'5':['NP','segment 5','nucleocapside protein','segment: 5'],
              '6':['neuraminidase', 'NA','segment 6','segment: 6'],'7':['segment 7','M1','M2','matrix protein','segment: 7'],
              '8':['segment 8', 'NS1' ,'NS2', 'NEP', 'nonstructural protein', 'nuclear export protein','segment: 8']}
iupac_to_int={'PB2':1,'PB1':2,'PA':3,'HA':4,'NP':5,'NA':6,'MP':7,'NS':8}
int_to_iupac={k:v for v,k in iupac_to_int.items()}
flagdict={"Fasta Preprocess":{"Rejected Sequences":[]},"Master":{"C_BLAST":True,"L_BLAST":True,"flumut":True,"genin":True,"nextclade":True,"getref":False,"single":True}, 
          "CD-HIT":{"Unclustered Sequences":[]},
          "BLAST":{"Sequences unassigned against cluster representatives":[],"Sequences unassigned against local database":[]},
          'Sample':{'HA':[],'NA':[],'PB2':[],'PB1':[],'PA':[],'NP':[],'MP':[],'NS':[],'Genotype':'','HA_ref':[],'NA_ref':[],
                    'PB2_ref':[],'PB1_ref':[], 'PA_ref':[], 'NP_ref':[],'MP_ref':[],'NS_ref':[],'PB2_len':0,'PB1_len':0,
                    'PA_len':0,'HA_len':0,'NP_len':0,'MP_len':0,'NA_len':0,'NS_len':0,'H_gen':'','N_gen':'',"clade":'','HA_muts':[],
                    'NA_muts':[],'PB2_muts':[],'PB1_muts':[],'PA_muts':[],'NP_muts':[],'MP_muts':[],'NS_muts':[],},
          "Final Report":{"Sequences for FluMut":[],"Sequences for NextClade":{'H1':[],'H3':[],'H5':[]},"Sequences for GenIn":[],'Get References':[]}}
iupac_nucleotides={'A':'A','C':'C','G':'G','T':'T','R':'AG','Y':'CT','S':'GC','W':'AT','K':'GT','M':'AC','B':'CGT','D':'AGT','H':'ACT','V':'ACG','N':'N'}
taxa_dict={'Human': ['Homo sapiens','Homo','Homininae','Hominidae','Hominoidea','Primates','Mammalia'],
 'Pig (Boar and Domestic)': ['Sus scrofa','Sus','Suinae','Suidae','Suina','Artiodactyla','Mammalia'],
 'Pig (Domestic)': ['Sus scrofa scrofa','Sus','Suinae','Suidae','Suina','Artiodactyla','Mammalia'],
 'Chicken (Red Junglefowl)': ['Gallus gallus','Gallus','Phasianinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Mallard duck': ['Anas platyrhynchos','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Ducks, swan and geese (family)': ['X','X','X','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Ruddy turnstone': ['Arenaria interpres','Arenaria','Arenariinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Birds (class)': ['X', 'X', 'X', 'X', 'X', 'X', 'Aves'],
 'Blue-winged Teal': ['Spatula discors','Spatula','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Turkey': ['Meleagris gallopavo','Meleagris','Meleagridinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Horse': ['Equus caballus','Equus','Equinae','Equidae','Hippomorpha','Perissodactyla','Mammalia'],
 'Northern pintail': ['Anas acuta','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Cattle': ['Bos taurus','Bos','Bovinae','Bovidae','Pecora','Artiodactyla','Mammalia'],
 'Ducks, teals and pintails (genus)': ['X','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Green-winged teal': ['Anas carolinensis','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Dog': ['Canis lupus familiaris','Canis','Caninae','Canidae','Caniformia','Carnivora','Mammalia'],
 'Muscovy duck': ['Cairina moschata','Cairina','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Black-headed gull': ['Chroicocephalus ridibundus','Chroicocephalus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Northern shoveler': ['Spatula clypeata','Spatula','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'American black duck': ['Anas rubripes','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Snow goose': ['Anser caerulescens','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Eurasian teal': ['Anas crecca','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Glaucous-winged gull': ['Larus glaucescens','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Bald eagle': ['Haliaeetus leucocephalus','Haliaeetus','Haliaeetinae','Accipitridae','X','Accipitriformes','Aves'],
 'Waterfowl (order)': ['X', 'X', 'X', 'X', 'X', 'Anseriformes', 'Aves'],
 'American widgeon': ['Mareca americana','Mareca','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Pidgeons and doves (family)': ['X','X','X','Columbidae','X','Columbiformes','Aves'],
 'Greater white-fronted goose': ['Anser albifrons','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Canada goose': ['Branta canadensis','Branta','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Guineafowl (family)': ['X','X','X','Numididae','Phasianoidea','Galliformes','Aves'],
 'Gadwall': ['Mareca strepera','Mareca','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Landfowl (order)': ['X', 'X', 'X', 'X', 'X', 'Galliformes', 'Aves'],
 'Laughing Gull': ['Leucophaeus atricilla','Leucophaeus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Sanderling': ['Calidris alba','Calidris','Calidrinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Red Knot': ['Calidris canutus','Calidris','Calidrinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Black Vulture': ['Coragyps atratus','Coragyps','Cathartinae','Cathartidae','X','Accipitriformes','Aves'],
 'Herring Gull': ['Larus argentatus','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Mute Swan': ['Cygnus olor','Cygnus','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Cinereous Vulture': ['Aegypius monachus','Aegypius','Aegypiinae','Accipitridae','X','Accipitriformes','Aves'],
 'Chicken, turkey and quail (family)': ['X','X','X','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Great Horned Owl': ['Bubo virginianus','Bubo','Buboninae','Strigidae','X','Strigiformes','Aves'],
 'Bean Goose': ['Anser fabalis','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Ring-billed Gull': ['Larus delawarensis','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Seagulls and terns (family)': ['X','X','X','Laridae','Lari','Charadriiformes','Aves'],
 'Red-tailed Hawk': ['Buteo jamaicensis','Buteo','Buteoninae','Accipitridae','X','Accipitriformes','Aves'],
 'Common Goldeneye': ['Bucephala clangula','Bucephala','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Domestic Cat': ['Felis catus','Felis','Felinae','Felidae','Feliformia','Carnivora','Mammalia'],
 'Emperor Goose': ['Anser canagicus','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Thick-billed Murre': ['Uria lomvia','Uria','Alcinae','Alcidae','Lari','Charadriiformes','Aves'],
 'Kelp Gull': ['Larus dominicanus','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Landfowl (family)': ['X','X','X','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Common Murre': ['Uria aalge','Uria','Alcinae','Alcidae','Lari','Charadriiformes','Aves'],
 'Eurasian Wigeon': ['Mareca penelope','Mareca','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'European Mink': ['Mustela lutreola','Mustela','Mustelinae','Mustelidae','Caniformia','Carnivora','Mammalia'],
 'Baikal Teal': ['Sibirionetta formosa','Sibirionetta','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Quails (genus)': ['X','Coturnix','Perdicinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Lesser Scaup': ['Aythya affinis','Aythya','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Greylag Goose': ['Anser anser','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Tundra Swan': ['Cygnus columbianus','Cygnus','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Cinnamon Teal': ['Spatula cyanoptera','Spatula','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Wood Duck': ['Aix sponsa','Aix','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Semipalmated Sandpiper': ['Calidris pusilla','Calidris','Calidrinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Common Ostrich': ['Struthio camelus','Struthio','Struthioninae','Struthionidae','X','Struthioniformes','Aves'],
 'Whooper Swan': ['Cygnus cygnus','Cygnus','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Bufflehead': ['Bucephala albeola','Bucephala','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Grey Teal': ['Anas gracilis','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Crows and Ravens (genus)': ['X','Corvus','Corvinae','Corvidae','Eupasseres','Passeriformes','Aves'],
 'Yellow-billed Teal': ['Anas flavirostris','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Red-necked Stint': ['Calidris ruficollis','Calidris','Calidrinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Glaucous Gull': ['Larus hyperboreus','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Ring-necked Duck': ['Aythya collaris','Aythya','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Redhead': ['Aythya americana','Aythya','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 "Franklin's Gull": ['Leucophaeus pipixcan','Leucophaeus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Ibis (family)': ['X','X','X','Threskiornithidae','Ardei','Pelecaniformes','Aves'],
 'Pelicans (genus)': ['X','Pelecanus','Pelecaninae','Pelecanidae','Pelecani','Pelecaniformes','Aves'],
 'Chukar Partridge': ['Alectoris chukar','Alectoris','Perdicinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Ruddy Shelduck': ['Tadorna ferruginea','Tadorna','Tadorninae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Yellow-billed Pintail': ['Anas georgica','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Pacific Black Duck': ['Anas superciliosa','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Peregrine Falcon': ['Falco peregrinus','Falco','Falconinae','Falconidae','X','Falconiformes','Aves'],
 'Long-tailed Duck': ['Clangula hyemalis','Clangula','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'American Crow': ['Corvus brachyrhynchos','Corvus','Corvinae','Corvidae','Eupasseres','Passeriformes','Aves'],
 'Mandarin Duck': ['Aix galericulata','Aix','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Carnivores (order)': ['X', 'X', 'X', 'X', 'X', 'Carnivora', 'Mammalia'],
 'Lesser Black-backed Gull': ['Larus fuscus','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Goat': ['Capra hircus','Capra','Caprinae','Bovidae','Pecora','Artiodactyla','Mammalia'],
 "Bewick's Swan": ['Cygnus bewickii','Cygnus','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Great Black-backed Gull': ['Larus marinus','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Dunlin': ['Calidris alpina','Calidris','Calidrinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'South American Sea Lion': ['Otaria byronia','Otaria','Otariinae','Otariidae','Pinnipedia','Carnivora','Mammalia'],
 'Pidgeons (genus)': ['X','Columba','Columbinae','Columbidae','X','Columbiformes','Aves'],
 'Whimbrel': ['Numenius phaeopus','Numenius','Numeniinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Red Fox': ['Vulpes vulpes','Vulpes','Caninae','Canidae','Caniformia','Carnivora','Mammalia'],
 "Steller's Eider": ['Polysticta stelleri','Polysticta','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Royal Tern': ['Thalasseus maximus','Thalasseus','Sterninae','Laridae','Lari','Charadriiformes','Aves'],
 'Hooded Merganser': ['Lophodytes cucullatus','Lophodytes','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Peruvian Booby': ['Sula variegata','Sula','Sulinae','Sulidae','X','Suliformes','Aves'],
 'Black Skimmer': ['Rynchops niger','Rynchops','Rynchopinae','Laridae','Lari','Charadriiformes','Aves'],
 'Common Tern': ['Sterna hirundo','Sterna','Sterninae','Laridae','Lari','Charadriiformes','Aves'],
 'Snowy Owl': ['Bubo scandiacus','Bubo','Buboninae','Strigidae','X','Strigiformes','Aves'],
 'Seagulls (genus)': ['X','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Garganey': ['Spatula querquedula','Spatula','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Common Raven': ['Corvus corax','Corvus','Corvinae','Corvidae','Eupasseres','Passeriformes','Aves'],
 'Geese (genus)': ['X','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Griffon Vulture': ['Gyps fulvus','Gyps','Aegypiinae','Accipitridae','X','Accipitriformes','Aves'],
 'White-tailed Eagle': ['Haliaeetus albicilla','Haliaeetus','Haliaeetinae','Accipitridae','X','Accipitriformes','Aves'],
 'Peruvian Pelican': ['Pelecanus thagus','Pelecanus','Pelecaninae','Pelecanidae','Pelecani','Pelecaniformes','Aves'],
 'Hooded Crane': ['Grus monacha','Grus','Gruinae','Gruidae','Gruoidea','Gruiformes','Aves'],
 'Greater Scaup': ['Aythya marila','Aythya','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Pikas (family)': ['X','X','X','Ochotonidae','X','Lagomorfa','Mammalia'],
 'Cackling Goose': ['Branta hutchinsii','Branta','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Least Sandpiper': ['Calidris minutilla','Calidris','Calidrinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Tufted Duck': ['Aythya fuligula','Aythya','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 "Cooper's Hawk": ['Accipiter cooperii','Accipiter','Accipitrinae','Accipitridae','X','Accipitriformes','Aves'],
 'Harbor Seal': ['Phoca vitulina','Phoca','Phocinae','Phocidae','Pinnipedia','Carnivora','Mammalia'],
 'Yellow-legged Gull': ['Larus michahellis','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Collared doves (genus)': ['X','Streptopelia','Columbinae','Columbidae','X','Columbiformes','Aves'],
 'Common Coot': ['Fulica atra','Fulica','Rallinae','Rallidae','Ralli','Gruiformes','Aves'],
 'Pelicanids (family)': ['X','X','X','Pelecanidae','Pelecani','Pelecaniformes','Aves'],
 'Common eider': ['Somateria mollissima','Somateria','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Herons (family)': ['X','X','X','Ardeidae','Ardei','Pelecaniformes','Aves'],
 'Bar-headed Goose': ['Anser indicus','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Silver Teal': ['Anas versicolor','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'California Sea Lion': ['Zalophus californianus','Zalophus','Otariinae','Otariidae','Pinnipedia','Carnivora','Mammalia'],
 'Large-billed Crow': ['Corvus macrorhynchos','Corvus','Corvinae','Corvidae','Eupasseres','Passeriformes','Aves'],
 'Wild Horse': ['Equus ferus','Equus','Equinae','Equidae','Hippomorpha','Perissodactyla','Mammalia'],
 'Shorebirds (order)': ['X', 'X', 'X', 'X', 'X', 'Charadriiformes', 'Aves'],
 'Iceland gull': ['Larus glaucoides','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Rosy-billed Pochard': ['Netta peposaca','Netta','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'White-rumped Sandpiper': ['Calidris fuscicollis','Calidris','Calidrinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Skunks (family)': ['X','X','X','Mephitidae','Caniformia','Carnivora','Mammalia'],
 "Ross's Goose": ['Anser rossii','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Turkey vulture': ['Cathartes aura','Cathartes','Cathartinae','Cathartidae','X','Accipitriformes','Aves'],
 'American herring gull': ['Larus smithsonianus','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Black scoter': ['Melanitta americana','Melanitta','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Pinnipeds (clade)': ['X','X','X','X','Pinnipedia','Carnivora','Mammalia'],
 'Eagles, hawks and vultures (family)': ['X','X','X','Accipitridae','X','Accipitriformes','Aves'],
 'Black Swan': ['Cygnus atratus','Cygnus','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Comon Pochard': ['Aythya ferina','Aythya','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Common quail': ['Coturnix coturnix','Coturnix','Perdicinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'American White pelican': ['Pelecanus erythrorhynchos','Pelecanus','Pelecaninae','Pelecanidae','Pelecani','Pelecaniformes','Aves'],
 'Shelducks (genus)': ['X','Tadorna','Tadorninae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Racoon dog': ['Nyctereutes procyonoides','Nyctereutes','Caninae','Canidae','Caniformia','Carnivora','Mammalia'],
 'Old world sparrows (family)': ['X','X','X','Passeridae','Eupasseres','Passeriformes','Aves'],
 'Common Buzzard': ['Buteo buteo','Buteo','Buteoninae','Accipitridae','X','Accipitriformes','Aves'],
 'African Penguin': ['Spheniscus demersus','Spheniscus','Spheniscinae','Spheniscidae','X','Sphenisciformes','Aves'],
 'Common Shelduck': ['Tadorna tadorna','Tadorna','Tadorninae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Northern Elephant Seal': ['Mirounga angustirostris','Mirounga','Monachinae','Phocidae','Pinnipedia','Carnivora','Mammalia'],
 'Macaques (genus)': ['X','Macaca','Cercopithecinae','Cercopithecidae','Haplorhini','Primates','Mammalia'],
 'South Polar Skua': ['Stercorarius maccormicki','Stercorarius','Stercorariinae','Stercorariidae','Lari','Charadriiformes','Aves'],
 'Swan Goose': ['Anser cygnoides','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Chinstrap Penguin': ['Pygoscelis antarcticus','Pygoscelis','Pygoscelinae','Spheniscidae','X','Sphenisciformes','Aves'],
 'Mew Gull': ['Larus canus','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Emu': ['Dromaius novaehollandiae','Dromaius','Dromaiinae','Casuariidae','X','Casuariiformes','Aves'],
 'Red-shouldered Hawk': ['Buteo lineatus','Buteo','Buteoninae','Accipitridae','X','Accipitriformes','Aves'],
 'Falcated Duck': ['Mareca falcata','Mareca','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Brant Goose': ['Branta bernicla','Branta','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Gray Gull': ['Leucophaeus modestus','Leucophaeus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'American Coot': ['Fulica americana','Fulica','Rallinae','Rallidae','Ralli','Gruiformes','Aves'],
 'Brown-hooded Gull': ['Chroicocephalus maculipennis','Chroicocephalus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Coots (genus)': ['X','Fulica','Rallinae','Rallidae','Ralli','Gruiformes','Aves'],
 'Guanay cormorant': ['Leucocarbo bougainvillii','Leucocarbo','Phalacrocoracinae','Phalacrocoracidae','X','Suliformes','Aves'],
 'Corvids (family)': ['X','X','X','Corvidae','Eupasseres','Passeriformes','Aves'],
 'Eurasian Eagle-Owl': ['Bubo bubo','Bubo','Buboninae','Strigidae','X','Strigiformes','Aves'],
 'Ferruginous Duck': ['Aythya nyroca','Aythya','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Black-necked Swan': ['Cygnus melancoryphus','Cygnus','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Black-tailed Gull': ['Larus crassirostris','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Swans (genus)': ['X','Cygnus','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 "Belcher's gull": ['Larus belcheri','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Tiger': ['Panthera tigris','Panthera','Pantherinae','Felidae','Feliformia','Carnivora','Mammalia'],
 'Surf scoter': ['Melanitta perspicillata','Melanitta','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Eurasian curlew': ['Numenius arquata','Numenius','Numeniinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Blackish oystercatcher': ['Haematopus ater','Haematopus','Haematopodinae','Haematopodidae','Charadrii','Charadriiformes','Aves'],
 'Velvet scoter': ['Melanitta fusca','Melanitta','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Chesnut teal': ['Anas castanea','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Magpie-robins (genus)': ['X','Copsychus','Saxicolinae','Muscicapidae','Eupasseres','Passeriformes','Aves'],
 'Donkey': ['Equus asinus','Equus','Equinae','Equidae','Hippomorpha','Perissodactyla','Mammalia'],
 'Eurasian tree sparrow': ['Passer montanus','Passer','Passerinae','Passeridae','Eupasseres','Passeriformes','Aves'],
 'New World blackbirds (family)': ['X','X','X','Icteridae','Eupasseres','Passeriformes','Aves'],
 'Indian Peafowl': ['Pavo cristatus','Pavo','Phasianinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Black-headed Ibis': ['Anastomus oscitans','Anastomus','Threskiornithinae','Threskiornithidae','Ardei','Pelecaniformes','Aves'],
 'Great Crested Grebe': ['Podiceps cristatus','Podiceps','Podicipedinae','Podicipedidae','X','Podicipediformes','Aves'],
 'Adèlie Penguin': ['Pygoscelis adeliae','Pygoscelis','Pygoscelinae','Spheniscidae','X','Sphenisciformes','Aves'],
 'House Mouse': ['Mus musculus','Mus','Murinae','Muridae','Myomorpha','Rodentia','Mammalia'],
 'Maned Duck': ['Chenonetta jubata','Chenonetta','Tadorninae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Vaquita': ['Phocoena spinipinnis','Phocoena','Phocoeninae','Phocoenidae','Cetacea','Artiodactyla','Mammalia'],
 'American Oystercatcher': ['Haematopus palliatus','Haematopus','Haematopodinae','Haematopodidae','Charadrii','Charadriiformes','Aves'],
 'Lion': ['Panthera leo','Panthera','Pantherinae','Felidae','Feliformia','Carnivora','Mammalia'],
 'Javanese Whistling Duck': ['Dendrocygna javanica','Dendrocygna','Dendrocygninae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'White-cheeked Pintail': ['Anas undulata','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'King Eider': ['Somateria spectabilis','Somateria','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Rock Pigeon': ['Columba livia','Columba','Columbinae','Columbidae','X','Columbiformes','Aves'],
 'Barnacle Goose': ['Branta leucopsis','Branta','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Yellow-billed Tern': ['Thalasseus acuflavidus','Thalasseus','Sterninae','Laridae','Lari','Charadriiformes','Aves'],
 'Pink-footed Goose': ['Anser brachyrhynchus','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Great Grebe': ['Podiceps major','Podiceps','Podicipedinae','Podicipedidae','X','Podicipediformes','Aves'],
 'Harlequin Duck': ['Histrionicus histrionicus','Histrionicus','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Sandpipers (genus)': ['X','Calidris','Calidrinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Horses, donkeys and zebra (Genus)': ['X','Equus','Equinae','Equidae','Hippomorpha','Perissodactyla','Mammalia'],
 'Barn Swallow': ['Hirundo rustica','Hirundo','Hirundininae','Hirundinidae','Eupasseres','Passeriformes','Aves'],
 'Common Kestrel': ['Falco tinnunculus','Falco','Falconinae','Falconidae','X','Falconiformes','Aves'],
 'Ruddy Duck': ['Oxyura jamaicensis','Oxyura','Oxyurinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Sabine’s Gull': ['Xema sabini','Xema','X','Laridae','Lari','Charadriiformes','Aves'],
 'Grey Heron': ['Ardea cinerea','Ardea','Ardeinae','Ardeidae','Ardei','Pelecaniformes','Aves'],
 'Scoters (genus)': ['X','Melanitta','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Domesticated Ferret': ['Mustela putorius furo','Mustela','Mustelinae','Mustelidae','Caniformia','Carnivora','Mammalia'],
 'Slaty-backed Gull': ['Larus schistisagus','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Neotropic Cormorant': ['Phalacrocorax brasilianus','Phalacrocorax','Phalacrocoracinae','Phalacrocoracidae','X','Suliformes','Aves'],
 'Black-bellied Whistling-Duck': ['Dendrocygna autumnalis','Dendrocygna','Dendrocygninae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Red-necked Grebe': ['Podiceps grisegena','Podiceps','Podicipedinae','Podicipedidae','X','Podicipediformes','Aves'],
 'Canvasback': ['Aythya valisineria','Aythya','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Scaly-breasted Munia': ['Lonchura punctulata','Lonchura','Lonchurinae','Estrildidae','Eupasseres','Passeriformes','Aves'],
 'Eastern Buzzard': ['Buteo japonicus','Buteo','Buteoninae','Accipitridae','X','Accipitriformes','Aves'],
 'Little Yellow-shouldered Bat': ['Sturnira lilium','Sturnira','Sturnirinae','Phyllostomidae','Yangochiroptera','Chiroptera','Mammalia'],
 'Purple Heron': ['Ardea purpurea','Ardea','Ardeinae','Ardeidae','Ardei','Pelecaniformes','Aves'],
 'Psittacines (family)': ['X','X','X','Psittacidae','Psitacoidea','Psitaciformes','Aves'],
 'Sharp-tailed Sandpiper': ['Calidris acuminata','Calidris','Calidrinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Northern Goshawk': ['Accipiter gentilis','Accipiter','Accipitrinae','Accipitridae','X','Accipitriformes','Aves'],
 'Inca Tern': ['Larosterna inca','Larosterna','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Great-tailed Grackle': ['Quiscalus mexicanus','Quiscalus','Icterinae','Icteridae','Eupasseres','Passeriformes','Aves'],
 'Little Grebe': ['Tachybaptus ruficollis','Tachybaptus','Podicipedinae','Podicipedidae','X','Podicipediformes','Aves'],
 'House Crow': ['Corvus splendens','Corvus','Corvinae','Corvidae','Eupasseres','Passeriformes','Aves'],
 'Mergansers (genus)': ['X','Mergus','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Great Blue Heron': ['Ardea herodias','Ardea','Ardeinae','Ardeidae','Ardei','Pelecaniformes','Aves'],
 'Alpaca': ['Vicugna pacos','Vicugna','Caviinae','Camelidae','Tylopoda','Artiodactyla','Mammalia'],
 'Black-crowned Night Heron': ['Nycticorax nycticorax','Nycticorax','Nycticoracinae','Ardeidae','Ardei','Pelecaniformes','Aves'],
 'Elegant Tern': ['Thalasseus elegans','Thalasseus','Sterninae','Laridae','Lari','Charadriiformes','Aves'],
 'Black-necked Stilt': ['Himantopus melanurus','Himantopus','Recurvirostrinae','Recurvirostridae','Charadrii','Charadriiformes','Aves'],
 'Black-billed Magpie': ['Pica hudsonia','Pica','Corvinae','Corvidae','Eupasseres','Passeriformes','Aves'],
 'Cormorants (family)': ['X','X','X','Phalacrocoracidae','X','Suliformes','Aves'],
 'Twite': ['Linaria flavirostris','Linaria','Carduelinae','Fringillidae','Eupasseres','Passeriformes','Aves'],
 'Japanese Quail': ['Coturnix japonica','Coturnix','Perdicinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Oriental Magpie Robin': ['Copsychus saularis','Copsychus','Saxicolinae','Muscicapidae','Eupasseres','Passeriformes','Aves'],
 'Caspian Seal': ['Pusa caspica','Pusa','Phocinae','Phocidae','Pinnipedia','Carnivora','Mammalia'],
 'Little Egret': ['Egretta garzetta','Egretta','Ardeinae','Ardeidae','Ardei','Pelecaniformes','Aves'],
 'Black Swift': ['Cypseloides niger','Cypseloides','Apodinae','Apodidae','X','Apodiformes','Aves'],
 'Gyrfalcon': ['Falco rusticolus','Falco','Falconinae','Falconidae','X','Falconiformes','Aves'],
 'Falcons (genus)': ['X','Falco','Falconinae','Falconidae','X','Falconiformes','Aves'],
 'Turkeys (genus)': ['X','Meleagris','Meleagridinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Tawny Frogmouth': ['Podargus strigoides','Podargus','Podarginae','Podargidae','X','Caprimulgiformes','Aves'],
 'Helmeted Guineafowl': ['Numida meleagris','Numida','Numidinae','Numididae','Phasianoidea','Galliformes','Aves'],
 'South American Tern': ['Sterna hirundinacea','Sterna','Sterninae','Laridae','Lari','Charadriiformes','Aves'],
 'House Sparrow': ['Passer domesticus','Passer','Passerinae','Passeridae','Eupasseres','Passeriformes','Aves'],
 'Willet': ['Tringa semipalmata','Tringa','Tringinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'California Gull': ['Larus californicus','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Demoiselle Crane': ['Grus virgo','Grus','Gruinae','Gruidae','Gruoidea','Gruiformes','Aves'],
 'Wedge-tailed Shearwater': ['Ardenna pacifica','Ardenna','Procellariinae','Procellariidae','X','Procellariformes','Aves'],
 'Japanese White-eye': ['Zosterops japonicus','Zosterops','Zosteropinae','Zosteropidae','Eupasseres','Passeriformes','Aves'],
 'Lituratus Bat': ['Artibeus lituratus','Artibeus','Stenodermatinae','Phyllostomidae','Yangochiroptera','Chiroptera','Mammalia'],
 'Owls (family)': ['X', 'X', 'X', 'Strigidae', 'X', 'Strigiformes', 'Aves'],
 'Sacred Ibis': ['Threskiornis aethiopicus','Threskiornis','Threskiornithinae','Threskiornithidae','Ardei','Pelecaniformes','Aves'],
 'Brown-headed Gull': ['Chroicocephalus brunnicephalus','Chroicocephalus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Egyptian Goose': ['Alopochen aegyptiaca','Alpochen','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Armenian Gull': ['Larus armenicus','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Blue Goose': ['Anser caerulescens caerulescens','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Kalij Pheasant': ['Lophura nycthemera','Lophura','Phasianinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Red-crowned Crane': ['Grus japonensis','Grus','Gruinae','Gruidae','Gruoidea','Gruiformes','Aves'],
 'Black-headed Gull': ['Ichthyaetus melanocephalus','Ichthyaetus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Muskrat': ['Ondatra zibethicus','Ondatra','Arvicolinae','Cricetidae','Myomorpha','Rodentia','Mammalia'],
 'American Robin': ['Turdus migratorius','Turdus','Turdinae','Turdidae','Eupasseres','Passeriformes','Aves'],
 'Double-crested Cormorant': ['Phalacrocorax auritus','Phalacrocorax','Phalacrocoracinae','Phalacrocoracidae','X','Suliformes','Aves'],
 'Eurasian Blackbird': ['Turdus merula','Turdus','Turdinae','Turdidae','Eupasseres','Passeriformes','Aves'],
 'Whiskered Tern': ['Chlidonias hybrida','Chlidonias','Sterninae','Laridae','Lari','Charadriiformes','Aves'],
 'South American Dolphin': ['Cephalorhynchus eutropia','Cephalorhynchus','Delphininae','Delphinidae','Cetacea','Artiodactyla','Mammalia'],
 'Raccoon': ['Procyon lotor','Procyon','Procyoninae','Procyonidae','Caniformia','Carnivora','Mammalia'],
 'European Badger': ['Meles leucurus','Meles','Mustelinae','Mustelidae','Caniformia','Carnivora','Mammalia'],
 'Australian Pink-eared Duck': ['Malacorhynchus membranaceus','Malacorhynchus','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Australian Shelduck': ['Tadorna tadornoides','Tadorna','Tadorninae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Silver Gull': ['Chroicocephalus novaehollandiae','Chroicocephalus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Moorhen (family)': ['X','Gallinula','Gallinulinae','Rallidae','Ralli','Gruiformes','Aves'],
 'Dalmatian Pelican': ['Pelecanus crispus','Pelecanus','Pelecaninae','Pelecanidae','Pelecani','Pelecaniformes','Aves'],
 'Sandhill Crane': ['Antigone canadensis','Antigone','Gruinae','Gruidae','Gruoidea','Gruiformes','Aves'],
 'Coscoroba Swan': ['Coscoroba coscoroba','Coscoroba','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Red-gartered coot': ['Fulica armillata','Fulica','Rallinae','Rallidae','Ralli','Gruiformes','Aves'],
 'Black-legged Kittiwake': ['Rissa tridactyla','Rissa','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Thrushes (family)': ['X','X','X','Turdidae','Eupasseres','Passeriformes','Aves'],
 'Saker Falcon': ['Falco cherrug','Falco','Falconinae','Falconidae','X','Falconiformes','Aves'],
 'Grater Flamingo': ['Phoenicopterus roseus','Phoenicopterus','Phoenicopterinae','Phoenicopteridae','X','Phoenicopteriformes','Aves'],
 'Siberian Crane': ['Antigone vipio','Antigone','Gruinae','Gruidae','Gruoidea','Gruiformes','Aves'],
 'Striped Skunk': ['Mephitis mephitis','Mephitis','Mephitinae','Mephitidae','Caniformia','Carnivora','Mammalia'],
 'Brown Pelican': ['Pelecanus occidentalis','Pelecanus','Pelecaninae','Pelecanidae','Pelecani','Pelecaniformes','Aves'],
 'Green Peafowl': ['Pavo muticus','Pavo','Phasianinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Cheetah': ['Acinonyx jubatus','Acinonyx','Felinae','Felidae','Feliformia','Carnivora','Mammalia'],
 'Western Sandpiper': ['Calidris mauri','Calidris','Calidrinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Common Scoter': ['Melanitta nigra','Melanitta','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Mule': ['Equus asinus x Equus caballus','Equus','Equinae','Equidae','Hippomorpha','Perissodactyla','Mammalia'],
 'Common Starling': ['Sturnus vulgaris','Sturnus','Sturninae','Sturnidae','Eupasseres','Passeriformes','Aves'],
 'Sloth Bear': ['Melursus ursinus','Melursus','Ursinae','Ursidae','Caniformia','Carnivora','Mammalia'],
 'Viverrids (family)': ['X','X','X','Viverridae','Feliformia','Carnivora','Mammalia'],
 'Common Snipe': ['Gallinago gallinago','Gallinago','Scolopacinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Przewalskii Horse': ['Equus przewalskii','Equus','Equinae','Equidae','Hippomorpha','Perissodactyla','Mammalia'],
 'Red-crested Pochard': ['Netta rufina','Netta','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Red-winged Tinamou': ['Rhynchotus rufescens','Rhynchotus','Rhinocryptinae','Tinamidae','X','Tinamiformes','Aves'],
 'Crested Goshawk': ['Accipiter trivirgatus','Accipiter','Accipitrinae','Accipitridae','X','Accipitriformes','Aves'],
 'Lesser White-fronted Goose': ['Anser erythropus','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Long-finned Pilot Whale': ['Globicephala melas','Globicephala','Globicephalinae','Delphinidae','Cetacea','Artiodactyla','Mammalia'],
 'Chinese Francolin': ['Francolinus pintadeanus','Francolinus','Phasianinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Yellow-breasted Waxbill': ['Leiothrix lutea','Leiothrix','Timaliinae','Timaliidae','Eupasseres','Passeriformes','Aves'],
 'Common Hill Mynah': ['Gracula religiosa','Gracula','Sturninae','Sturnidae','Eupasseres','Passeriformes','Aves'],
 'White-rumped Munia': ['Lonchura striata','Lonchura','Lonchurinae','Estrildidae','Eupasseres','Passeriformes','Aves'],
 'Grebes (order)': ['X', 'X', 'X', 'X', 'X', 'Podicipediformes', 'Aves'],
 'Sandpipers (family)': ['X','X','X','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Red-billed Blue Magpie': ['Urocissa erythroryncha','Urocissa','Corvinae','Corvidae','Eupasseres','Passeriformes','Aves'],
 'Horned Puffin': ['Fratercula corniculata','Fratercula','Fraterculinae','Alcidae','Lari','Charadriiformes','Aves'],
 'Canvasbacks and Pochards (genus)': ['X','Aythya','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Great Cormorant': ['Phalacrocorax carbo','Phalacrocorax','Phalacrocoracinae','Phalacrocoracidae','X','Suliformes','Aves'],
 'Yellow-headed Amazon': ['Amazona oratrix','Amazona','Arinae','Psittacidae','Psitacoidea','Psitaciformes','Aves'],
 'European Starling': ['Agropsar sturninus','Agropsar','Sturninae','Sturnidae','Eupasseres','Passeriformes','Aves'],
 'European Magpie': ['Pica pica','Pica','Corvinae','Corvidae','Eupasseres','Passeriformes','Aves'],
 'Western Grebe': ['Aechmophorus occidentalis','Aechmophorus','Podicipedinae','Podicipedidae','X','Podicipediformes','Aves'],
 'Spectacled Eider': ['Somateria fischeri','Somateria','Merginae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Silk Starling': ['Sturnus sericeus','Sturnus','Sturninae','Sturnidae','Eupasseres','Passeriformes','Aves'],
 'Brambling': ['Fringilla montifringilla','Fringilla','Carduelinae','Fringillidae','Eupasseres','Passeriformes','Aves'],
 'Black-headed Munia': ['Lonchura atricapilla','Lonchura','Lonchurinae','Estrildidae','Eupasseres','Passeriformes','Aves'],
 'Eagles, hawks and vultures (order)': ['X','X','X','X','X','Accipitriformes','Aves'],
 'Tibetan Pika': ['Ochotona curzoniae','Ochotona','Ochotoninae','Ochotonidae','X','Lagomorfa','Mammalia'],
 'Grey-headed Swamphen': ['Gallicrex cinerea','Gallicrex','Rallinae','Rallidae','Ralli','Gruiformes','Aves'],
 'Brown Shrike': ['Lanius schach','Lanius','Laniinae','Laniidae','Eupasseres','Passeriformes','Aves'],
 'Marabou Stork': ['Leptoptilos crumeniferus','Leptoptilos','Ciconiinae','Ciconiidae','X','Ciconiiformes','Aves'],
 'Eurasian Sparrowhawk': ['Accipiter nisus','Accipiter','Accipitrinae','Accipitridae','X','Accipitriformes','Aves'],
 'Stonechat': ['Saxicola torquatus','Saxicola','Saxicolinae','Muscicapidae','Eupasseres','Passeriformes','Aves'],
 'Shrikes (family)': ['X','X','X','Laniidae','Eupasseres','Passeriformes','Aves'],
 'Pacific Golden-Plover': ['Pluvialis fulva','Pluvialis','Charadriinae','Charadriidae','Charadrii','Charadriiformes','Aves'],
 'Rheas (genus)': ['X','Rhea','Rheinae','Rheidae','X','Rheiformes','Aves'],
 'Bactrian Camel': ['Camelus bactrianus','Camelus','Camelinae','Camelidae','Tylopoda','Artiodactyla','Mammalia'],
 'Giant Panda': ['Ailuropoda melanoleuca','Ailuropoda','Ailuropodinae','Ursidae','Caniformia','Carnivora','Mammalia'],
 'Indian Skimmer': ['Ichthyaetus ichthyaetus','Ichthyaetus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Bengal Tiger': ['Panthera tigris tigris','Panthera','Pantherinae','Felidae','Feliformia','Carnivora','Mammalia'],
 'Flat-faced Fruit-eating Bat': ['Artibeus planirostris','Artibeus','Stenodermatinae','Phyllostomidae','Yangochiroptera','Chiroptera','Mammalia'],
 'Rook': ['Corvus frugilegus','Corvus','Corvinae','Corvidae','Eupasseres','Passeriformes','Aves'],
 'Finches (family)': ['X','X','X','Fringillidae','Eupasseres','Passeriformes','Aves'],
 'Eurasian Woodcock': ['Scolopax rusticola','Scolopax','Scolopacinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'White-bellied Bustard': ['Eupodotis senegalensis','Eupodotis','Otidinae','Otididae','X','Otidiformes','Aves'],
 'Great Egret': ['Ardea alba','Ardea','Ardeinae','Ardeidae','Ardei','Pelecaniformes','Aves'],
 'Silver-eared Mesia': ['Leiothrix argentauris','Leiothrix','Timaliinae','Timaliidae','Eupasseres','Passeriformes','Aves'],
 'Earless seals (family)': ['X','X','X','Phocidae','Pinnipedia','Carnivora','Mammalia'],
 'Chinese Hwamei': ['Garrulax canorus','Garrulax','Timaliinae','Timaliidae','Eupasseres','Passeriformes','Aves'],
 'Lesser Kestrel': ['Falco naumanni','Falco','Falconinae','Falconidae','X','Falconiformes','Aves'],
 "Baer's Pochard": ['Aythya baeri','Aythya','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Common Bottlenose Dolphin': ['Tursiops truncatus','Tursiops','Delphininae','Delphinidae','Cetacea','Artiodactyla','Mammalia'],
 'Grey Plover': ['Pluvialis squatarola','Pluvialis','Charadriinae','Charadriidae','Charadrii','Charadriiformes','Aves'],
 'Caspian Tern': ['Hydroprogne caspia','Hydroprogne','Sterninae','Laridae','Lari','Charadriiformes','Aves'],
 'Fish Crow': ['Corvus ossifragus','Corvus','Corvinae','Corvidae','Eupasseres','Passeriformes','Aves'],
 'Common Pheasant': ['Phasianus colchicus','Phasianus','Phasianinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Sharp-shinned Hawk': ['Accipiter striatus','Accipiter','Accipitrinae','Accipitridae','X','Accipitriformes','Aves'],
 'Vega Gull': ['Larus vegae','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Short-beaked Common Dolphin': ['Delphinus delphis','Delphinus','Delphininae','Delphinidae','Cetacea','Artiodactyla','Mammalia'],
 'Humboldt Penguin': ['Spheniscus humboldti','Spheniscus','Spheniscinae','Spheniscidae','X','Sphenisciformes','Aves'],
 'Chiloe Wigeon': ['Mareca sibilatrix','Mareca','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Chilean Flamingo': ['Phoenicopterus chilensis','Phoenicopterus','Phoenicopterinae','Phoenicopteridae','X','Phoenicopteriformes','Aves'],
 'Brown Rat': ['Rattus norvegicus','Rattus','Murinae','Muridae','Myomorpha','Rodentia','Mammalia'],
 'Crested Fireback': ['Lophura ignita','Lophura','Phasianinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Black-headed Duck': ['Heteronetta atricapilla','Heteronetta','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Southern Lapwing': ['Vanellus chilensis','Vanellus','Charadriinae','Charadriidae','Charadrii','Charadriiformes','Aves'],
 'Plumed Whistling Duck': ['Dendrocygna eytoni','Dendrocygna','Dendrocygninae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Masked Palm Civet': ['Paguma larvata','Paguma','Paradoxurinae','Viverridae','Feliformia','Carnivora','Mammalia'],
 'Canids (family)': ['X','X','X','Canidae','Caniformia','Carnivora','Mammalia'],
 'Giant Anteater': ['Myrmecophaga tridactyla','Myrmecophaga','Myrmecophaginae','Myrmecophagidae','Vermilingua','Pilosa','Mammalia'],
 'Equids (family)': ['X','X','X','Equidae','Hippomorpha','Perissodactyla','Mammalia'],
 'Common Loon': ['Gavia immer','Gavia','Gaviinae','Gaviidae','X','Gaviiformes','Aves'],
 'Magnificent Frigatebird': ['Fregata magnificens','Fregata','Fregatinae','Fregatidae','X','Suliformes','Aves'],
 'Jackal Buzzard': ['Buteo rufofuscus','Buteo','Buteoninae','Accipitridae','X','Accipitriformes','Aves'],
 'Polar Bear': ['Ursus maritimus','Ursus','Ursinae','Ursidae','Caniformia','Carnivora','Mammalia'],
 'Marine Otter': ['Lontra felina','Lontra','Mustelinae','Mustelidae','Caniformia','Carnivora','Mammalia'],
 'Woodpeckers (family)': ['X','X','X','Picidae','Pici','Piciformes','Aves'],
 'Tropical Screech Owl': ['Megascops choliba','Megascops','Striginae','Strigidae','X','Strigiformes','Aves'],
 'Brown Booby': ['Sula leucogaster','Sula','Sulinae','Sulidae','X','Suliformes','Aves'],
 'Great Black Hawk': ['Buteogallus urubitinga','Buteogallus','Accipitrinae','Accipitridae','X','Accipitriformes','Aves'],
 'White-chinned Petrel': ['Procellaria aequinoctialis','Procellaria','Procellariinae','Procellariidae','X','Procellariformes','Aves'],
 'American Golden Plover': ['Pluvialis dominica','Pluvialis','Charadriinae','Charadriidae','Charadrii','Charadriiformes','Aves'],
 'Arctic Tern': ['Sterna paradisaea','Sterna','Sterninae','Laridae','Lari','Charadriiformes','Aves'],
 'Brush-tailed penguins (genus)': ['X','Pygoscelis','Pygoscelinae','Spheniscidae','X','Sphenisciformes','Aves'],
 'American Black Bear': ['Ursus americanus','Ursus','Ursinae','Ursidae','Caniformia','Carnivora','Mammalia'],
 'Western Gull': ['Larus occidentalis','Larus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Trumpeter Swan': ['Cygnus buccinator','Cygnus','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'South American Fur Seal': ['Arctocephalus australis','Arctocephalus','Otariinae','Otariidae','Pinnipeda','Carnivora','Mammalia'],
 'Egyptian Fruit Bat': ['Rousettus aegyptiacus','Rousettus','Rousettinae','Pteropodidae','Yinpterochiroptera','Chiroptera','Mammalia'],
 'Short-billed Dowitcher': ['Limnodromus griseus','Limnodromus','Scolopacinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Chimango Caracara': ['Milvago chimango','Milvago','Falconinae','Falconidae','X','Falconiformes','Aves'],
 'Old world cormorants (genus)': ['X','Phalacrocorax','Phalacrocoracinae','Phalacrocoracidae','X','Suliformes','Aves'],
 'American Flamingo': ['Phoenicopterus ruber','Phoenicopterus','Phoenicopterinae','Phoenicopteridae','X','Phoenicopteriformes','Aves'],
 'Sandwich Tern': ['Thalasseus sandvicensis','Thalasseus','Sterninae','Laridae','Lari','Charadriiformes','Aves'],
 'White-faced Whistling Duck': ['Dendrocygna viduata','Dendrocygna','Dendrocygninae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Grey-faced Buzzard': ['Butastur indicus','Butastur','Circinae','Accipitridae','X','Accipitriformes','Aves'],
 'Upland Goose': ['Chloephaga picta','Chloephaga','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Dolphin Gul': ['Leucophaeus scoresbii','Leucophaeus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Old world flycatchers (genus)': ['X','Muscicapa','Muscicapinae','Muscicapidae','Eupasseres','Passeriformes','Aves'],
 'Black-winged Stilt': ['Himantopus himantopus','Himantopus','Recurvirostrinae','Recurvirostridae','Charadrii','Charadriiformes','Aves'],
 'Silver -headed Gull': ['Chroicocephalus cirrocephalus','Chroicocephalus','Larinae','Laridae','Lari','Charadriiformes','Aves'],
 'Anser anser domesticus': ['Anser anser domesticus','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 "Von Schrenck's bittern": ['Ixobrychus eurhythmus','Ixobrychus','Ardeinae','Ardeidae','Ardei','Pelecaniformes','Aves'],
 'Black-necked Crane': ['Grus nigricollis','Grus','Gruinae','Gruidae','Gruoidea','Gruiformes','Aves'],
 'Ural Owl': ['Strix uralensis','Strix','Striginae','Strigidae','X','Strigiformes','Aves'],
 'Bats (order)': ['X', 'X', 'X', 'X', 'X', 'Chiroptera', 'Mammalia'],
 'Dark Fruit-eating Bat': ['Artibeus obscurus','Artibeus','Stenodermatinae','Phyllostomidae','Yangochiroptera','Chiroptera','Mammalia'],
 'Black-tailed Godwit': ['Limosa limosa','Limosa','Scolopacinae','Scolopacidae','Scolopaci','Charadriiformes','Aves'],
 'Weasels (genus)': ['X','Mustela','Mustelinae','Mustelidae','Caniformia','Carnivora','Mammalia'],
 'Common Moorhen': ['Gallinula chloropus','Gallinula','Gallinulinae','Rallidae','Ralli','Gruiformes','Aves'],
 "Pallas's Sandgrouse": ['Syrrhaptes paradoxus','Syrrhaptes','Tetraoninae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Night herons (genus)': ['X','Nycticorax','Nycticoracinae','Ardeidae','Ardei','Pelecaniformes','Aves'],
 'Bulbuls (family)': ['X','X','X','Pycnonotidae','Eupasseres','Passeriformes','Aves'],
 'Red Shoveler': ['Spatula platalea','Spatula','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Comb Duck': ['Sarkidiornis sylvicola','Sarkidiornis','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Cape Cormorant': ['Phalacrocorax capensis','Phalacrocorax','Phalacrocoracinae','Phalacrocoracidae','X','Suliformes','Aves'],
 'Domestic Swan Goose': ['Anser cygnoides domesticus','Anser','Anserinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Crowned Cormorant': ['Microcarbo coronatus','Microcarbo','Phalacrocoracinae','Phalacrocoracidae','X','Suliformes','Aves'],
 'African Black Oystercatcher': ['Haematopus moquini','Haematopus','Haematopodinae','Haematopodidae','Charadrii','Charadriiformes','Aves'],
 'Little Cormorant': ['Microcarbo niger','Microcarbo','Phalacrocoracinae','Phalacrocoracidae','X','Suliformes','Aves'],
 "Henri's Snowfinch": ['Montifringilla henrici','Montifringilla','Passerinae','Passeridae','Eupasseres','Passeriformes','Aves'],
 'Dromedary Camel': ['Camelus dromedarius','Camelus','Camelinae','Camelidae','Tylopoda','Artiodactyla','Mammalia'],
 'Mallard duck (wild)': ['Anas platyrhynchos platyrhynchos','Anas','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 "Northern Goshawk (Schvedow's subspecies)": ['Accipiter gentilis schvedowi','Accipiter','Accipitrinae','Accipitridae','X','Accipitriformes','Aves'],
 'Little Owl': ['Athene noctua','Athene','Striginae','Strigidae','X','Strigiformes','Aves'],
 'Striated Heron': ['Butorides striata','Butorides','Ardeinae','Ardeidae','Ardei','Pelecaniformes','Aves'],
 'White-winged Tern': ['Chlidonias leucopterus','Chlidonias','Sterninae','Laridae','Lari','Charadriiformes','Aves'],
 'Pidgeons and doves (order)': ['X','X','X','X','X','Columbiformes','Aves'],
 'Gentoo Penguin': ['Pygoscelis papua','Pygoscelis','Pygoscelinae','Spheniscidae','X','Sphenisciformes','Aves'],
 'Speckled Pigeon': ['Columba guinea','Columba','Columbinae','Columbidae','X','Columbiformes','Aves'],
 'Meerkat': ['Suricata suricatta','Suricata','Suricatinae','Herpestidae','Feliformia','Carnivora','Mammalia'],
 'Great Tit': ['Parus major','Parus','Parinae','Estrildidae','Eupasseres','Passeriformes','Aves'],
 'Great Bustard': ['Otis tarda','Otis','Otidinae','Otididae','X','Otidiformes','Aves'],
 'Brown Skua': ['Stercorarius lonnbergi','Stercorarius','Stercorariinae','Stercorariidae','Lari','Charadriiformes','Aves'],
 'Wigeons': ['X','Mareca','Anatinae','Anatidae','Anseriphormae','Anseriformes','Aves'],
 'Mammals (class)': ['X', 'X', 'X', 'X', 'X', 'X', 'Mammalia'],
 'Felids (family)': ['X','X','X','Felidae','Feliformia','Carnivora','Mammalia'],
 'Partridges (subfamily)': ['X','X','Perdicinae','Phasianidae','Phasianoidea','Galliformes','Aves'],
 'Swifts (subfamily)': ['X','X','Apodinae','Apodidae','X','Apodiformes','Aves']}
geo_dict=country_to_region_continent = {
    'USA': ('Northern America', 'North America'),'China': ('Eastern Asia', 'Asia'),'Korea': ('Eastern Asia', 'Asia'),'South Korea': ('Eastern Asia', 'Asia'),
    'Hong Kong': ('Eastern Asia', 'Asia'),'Bangladesh': ('Southern Asia', 'Asia'),'Senegal': ('Western Africa', 'Africa'),'Mexico': ('Central America', 'North America'),
    'Chile': ('South America', 'South America'),'Bolivia': ('South America', 'South America'),'Nigeria': ('Western Africa', 'Africa'),'Germany': ('Western Europe', 'Europe'),
    'Viet Nam': ('South-Eastern Asia', 'Asia'),'Kazakhstan': ('Central Asia', 'Asia'),'Egypt': ('Northern Africa', 'Africa'),'Switzerland': ('Western Europe', 'Europe'),
    'United Kingdom': ('Northern Europe', 'Europe'),'Australia': ('Australia and New Zealand', 'Oceania'),'Spain': ('Southern Europe', 'Europe'),'Russia': ('Eastern Europe', 'Europe'),
    'Canada': ('Northern America', 'North America'),'Taiwan': ('Eastern Asia', 'Asia'),'Brazil': ('South America', 'South America'),'Italy': ('Southern Europe', 'Europe'),
    'Serbia': ('Southern Europe', 'Europe'),'Japan': ('Eastern Asia', 'Asia'),'Laos': ('South-Eastern Asia', 'Asia'),'Uruguay': ('South America', 'South America'),
    'Thailand': ('South-Eastern Asia', 'Asia'),'Peru': ('South America', 'South America'),'Mali': ('Western Africa', 'Africa'),'Mozambique': ('Eastern Africa', 'Africa'),
    'Argentina': ('South America', 'South America'),'Pakistan': ('Southern Asia', 'Asia'),'Denmark': ('Northern Europe', 'Europe'),'Zambia': ('Eastern Africa', 'Africa'),
    'Gabon': ('Middle Africa', 'Africa'),'Tunisia': ('Northern Africa', 'Africa'),'India': ('Southern Asia', 'Asia'),'Mongolia': ('Eastern Asia', 'Asia'),
    'Malaysia': ('South-Eastern Asia', 'Asia'),'Cambodia': ('South-Eastern Asia', 'Asia'),'France': ('Western Europe', 'Europe'),'Iran': ('Southern Asia', 'Asia'),
    'Poland': ('Eastern Europe', 'Europe'),'Colombia': ('South America', 'South America'),'Myanmar': ('South-Eastern Asia', 'Asia'),'Guatemala': ('Central America', 'North America'),
    'Belgium': ('Western Europe', 'Europe'),'Netherlands': ('Western Europe', 'Europe'),'Uganda': ('Eastern Africa', 'Africa'),'Singapore': ('South-Eastern Asia', 'Asia'),
    'South Africa': ('Southern Africa', 'Africa'),'Lesotho': ('Southern Africa', 'Africa'),'Iceland': ('Northern Europe', 'Europe'),'Czech Republic': ('Eastern Europe', 'Europe'),
    'El Salvador': ('Central America', 'North America'),'Indonesia': ('South-Eastern Asia', 'Asia'),'Turkey': ('Western Asia', 'Asia'),'Saudi Arabia': ('Western Asia', 'Asia'),
    'Ukraine': ('Eastern Europe', 'Europe'),'Tajikistan': ('Central Asia', 'Asia'),'Benin': ('Western Africa', 'Africa'),'Dominican Republic': ('Caribbean', 'North America'),
    'Lithuania': ('Northern Europe', 'Europe'),'Morocco': ('Northern Africa', 'Africa'),'Togo': ('Western Africa', 'Africa'),'Bulgaria': ('Eastern Europe', 'Europe'),
    'Austria': ('Western Europe', 'Europe'),'Chad': ('Middle Africa', 'Africa'),'Iraq': ('Western Asia', 'Asia'),'Kenya': ('Eastern Africa', 'Africa'),
    'Zimbabwe': ('Southern Africa', 'Africa'),'Hungary': ('Eastern Europe', 'Europe'),'Ghana': ('Western Africa', 'Africa'),'Bahrain': ('Western Asia', 'Asia'),
    'United Arab Emirates': ('Western Asia', 'Asia'),'Antarctica': ('Antarctica', 'Antarctica'),'Algeria': ('Northern Africa', 'Africa'),'Nicaragua': ('Central America', 'North America'),
    'Democratic Republic of the Congo': ('Middle Africa', 'Africa'),'Cameroon': ('Middle Africa', 'Africa'),'Georgia': ('Western Asia', 'Asia'),'Jordan': ('Western Asia', 'Asia'),
    'Burkina Faso': ('Western Africa', 'Africa'),'Niger': ('Western Africa', 'Africa'),'Sweden': ('Northern Europe', 'Europe'),'Honduras': ('Central America', 'North America'),
    'Afghanistan': ('Southern Asia', 'Asia'),'Israel': ('Western Asia', 'Asia'),'Kosovo': ('Southern Europe', 'Europe'),'Bosnia and Herzegovina': ('Southern Europe', 'Europe'),
    'Ethiopia': ('Eastern Africa', 'Africa'),'Kuwait': ('Western Asia', 'Asia'),'Kyrgyzstan': ('Central Asia', 'Asia'),'Philippines': ('South-Eastern Asia', 'Asia'),
    'Bhutan': ('Southern Asia', 'Asia'),'Nepal': ('Southern Asia', 'Asia'),'Lebanon': ('Western Asia', 'Asia'),"Cote d'Ivoire": ('Western Africa', 'Africa'),
    'Greenland': ('Northern America', 'North America'),'Finland': ('Northern Europe', 'Europe'),'Sri Lanka': ('Southern Asia', 'Asia'),'Portugal': ('Southern Europe', 'Europe'),
    'Greece': ('Southern Europe', 'Europe'),'New Zealand': ('Australia and New Zealand', 'Oceania'),'New Caledonia': ('Melanesia', 'Oceania'),'Estonia': ('Northern Europe', 'Europe'),
    'Norway': ('Northern Europe', 'Europe'),'Ireland': ('Northern Europe', 'Europe'),'Ecuador': ('South America', 'South America'),'Slovenia': ('Southern Europe', 'Europe'),
    'Luxembourg': ('Western Europe', 'Europe'),'Qatar': ('Western Asia', 'Asia'),'Uzbekistan': ('Central Asia', 'Asia'),'Romania': ('Eastern Europe', 'Europe'),
    'Slovakia': ('Eastern Europe', 'Europe'),'Sudan': ('Northern Africa', 'Africa'),'Tonga': ('Polynesia', 'Oceania'),'Croatia': ('Southern Europe', 'Europe')
}

muts_interest={'HA': ['156A', '156V', '186D', '186V', '221D', '222L', '224S', '208T'],
 'NA': ['399R', '432E', '275Y', '119V', '292K', '223V'],
 'PA': ['356R', '552S', '85I', '97I', '336M', '186S', '38T'],
 'PB1': ['66S'],
 'PB2': ['271A','292V','526R','588I','588V','591K','591R',
  '627K','627V','631L','701N','702N','199S','9N','740N'],
 'MP': ['95K', '31N', '27A'],
 'NP': ['100I', '100V', '283P', '313V', '313Y', '52H', '52N']}

muts_loci_meaning={'156A':('HA:156A','Increased virus binding to α2,6, increased transmission in guinea pigs'), 
                   '156V':('HA:156V','Observed in seal samples; decreased virulence in mice and increased affinity for the human-type receptor'), 
                   '186D':('HA:186D','In combination with HA:221D; Switch in the receptor specificity from avian-type to human-type receptor'), 
                   '186V':('HA:186V','Enhances binding affinity to mammalian cells and replication in mammalian cells; enhanced replication in mice'),
                   '221D':('HA:221D','Increased virus binding to α2,6'), 
                   '222L':('HA:222L','Increased virus binding to α2,6; transmitted via aerosol among guinea pigs; enhanced replication in mammalian cells and ferrets, enhanced contact transmission in ferrets; Loss of binding to α2,3; Increased acid and thermal stability'), 
                   '224S':('HA:224S','Increased binding to α2,6; increased viral replication in mammalian cells and virulence in mice; observed in human isolate; increase in the ability of the virus to infect mammals; decreased virus binding to α2,3'), 
                   '208T':('HA:208T','Increased the viral replication in avian and mammalian cells; enhance viral replication in mice'),
                   '399R':('NA:399R','Mutation of 2SBS that are detrimental to the cleavage of sialosides linked to fetuin or transferrin; observed in seals'), 
                   '432E':('NA:432E','Decreased cleavage of fetuin-containing α2,3-linked sialic acids (SIAs) but not that of monovalent substrates or of transferrin containing only α2,6-linked SIAs'), 
                   '275Y':('NA:275Y','Resistance to antivirals: Oseltamivir and Peramivir'), 
                   '119V':('NA:119V','Resistance to antivirals: Zanamivir'), 
                   '292K':('NA:292K','Resistance to antivirals: Zanamivir'), 
                   '223V':('NA:223V','Resistance to antivirals: Laninamivir'),
                   '356R':('PA:356R','Human host marker; Increase polymerase activity and enhanced replication in a mammalian cell line, increased virulence in mice'), 
                   '552S':('PA:552S','Enhanced viral RNA-dependent RNA polymerase (vRdRp) activity and viral replication in vitro'), 
                   '85I':('PA:85I','Enables guanine-rich sequence binding factor (GRSF1) to enhance the cytosolic accumulation and translation of a subset of viral mRNAs; enhanced replication in human A549 cells'), 
                   '97I':('PA:97I','Increased polymerase activity in mammalian cell line and enhanced replication and virulence in mice; increased polymerase activity in mammalian'), 
                   '336M':('PA:336M','Significantly enhanced pathogenicity in a mouse model'), 
                   '186S':('PA:186S','	Enables GRSF1 to enhance the cytosolic accumulation and translation of a subset of viral mRNAs'), 
                   '38T':('PA:38T','Resistance to antivirals: Baloxavir Marboxil'),
                   '38M':('PA:38M','Resistance to antivirals: Baloxavir Marboxil'),
                   '38F':('PA:38F','Resistance to antivirals: Baloxavir Marboxil'),
                   '66S':('PB1-F2:66S','Increased virulence, replication efficiency and antiviral response in mice'),
                   '271A':('PB2:271A','Increase polymerase activity in the presence of avian acidic nuclear phosphoprotein 32 (ANP32) proteins; increase mortality and airborne transmission in ferrets; increased polymerase activity in avian and mammalian cell line'),
                   '292V':('PB2:292V','Observed in H3N8 samples from humans and birds; increased polymerase activity in a mammalian cell line, increased virulence in mice'),
                   '526R':('PB2:526R','Increased polymerase activity in mammalian cell line and virulence in mice'),
                   '588I':('PB2:588I','Enhances 2009 H1N1 pandemic influenza virus virulence by increasing viral replication and exacerbating PB2 inhibition of beta-interferon expression'),
                   '588V':('PB2:588V','Increased polymerase activity and replication in mammalian and avian cell lines, increased virulence in mice'),
                   '591K':('PB2:591K','Increased polymerase activity in mammalian and avian cell line, increased replication in a mammalian cell line, increased virulence in mice; observed in human isolates'),
                   '591R':('PB2:591R','Enhanced mammalian ANP32 adaptation (non-biased)'),
                   '627K':('PB2:627K','Observed in human isolate; increased polymerase activity and replication in mammalian cell line, increased virulence in mice and ferrets; contributes to airborne transmission of influenza A viruses (IAVs) in ferrets and contact transmission in guinea pigs; mammalian ANP32-specific adaptation (ANP32B biased)'),
                   '627V':('PB2:627V','Observed in human isolate; mammalian ANP32-specific adaptation (ANP32B biased); observed in human samples in Shenzhen; increased polymerase activity and replication in mammalian cell lines, increased virulence in mice'),
                   '631L':('PB2:631L','Most dominant mutation in mouse-adapted virus that strongly upregulated viral polymerase activity and played a critical role in the enhancement of virus replication and disease severity in mice; observed in dairy cattle USA 2024'),
                   '701N':('PB2:701N','Increased polymerase activity, enhanced replication efficiency, increased virulence and contact transmission in guinea pigs; increased polymerase activity in mammalian cell line; increased viral replication and virulence in mice; mammalian ANP32-specific adaptation (non-biased); observed in seals'),
                   '702N':('PB2:702N','Observed in human isolate; increased polymerase activity in human and avian cells'),
                   '199S':('PB2:199S','Increased virulence in mice'),
                   '9N':('PB2:9N','Observed in domestic poultry, Uganda; increased virulence in mice'),
                   '740N':('PB2:740N','Increase polymerase activity in the presence of avian ANP32 proteins, in human and avian cells'),
                   '95K':('M1:95K','Resistant to TRIM21, increases replication and pathogenicity in mice'),
                   '31N':('M2:31N','Increased resistance to adamantanes'),
                   '27A':('M2:27A','Increased resistance to adamantanes'),
                   '100I':('NP:100I','Resistance against Myxovirus resistance protein A (MxA)'),
                   '100V':('NP:100V','Resistance against Myxovirus resistance protein A (MxA)'),
                   '283P':('NP:283P','Resistance against Myxovirus resistance protein A (MxA)'),
                   '313V':('NP:313V','Role in Butyrophilin Subfamily 3 Member A3 (BTN3A3) evasion'),
                   '313Y':('NP:313Y','Role in Butyrophilin Subfamily 3 Member A3 (BTN3A3) evasion'),
                   '52H':('NP:52H','Role in Butyrophilin Subfamily 3 Member A3 (BTN3A3) evasion'),
                   '52N':('NP:52N','Significant mutation observed also in H5N1; role in BTN3A3 evasion')}

seg_lens={'PB2_min':2226, 'PB1_min':2211, 'PA_min':2294, 'HA_min':1640, 'NP_min':1431, 'NA_min':1364, 'MP_min':952, 'NS_min':798, 
          'PB2_max':2370, 'PB1_max':2379, 'PA_max':2606, 'HA_max':1804, 'NP_max':1607, 'NA_max':1488, 'MP_max':1032, 'NS_max':906}